#!/usr/bin/env bash

if [ ! -d tests ]; then
  echo 'Directory tests not found!'
  exit 1
fi

if [ ! -f "./test" ]; then
  echo "Executable test not found!"
  exit 2
fi

TEST_FILES=$(find tests -name '*.minilisp')

TESTS_NUMBER="$(wc -w <<< $TEST_FILES | sed 's/[^1-9]//g')"
passed_tests=0

for test_file in $TEST_FILES; do
  expected_result="$(head -1 $test_file | sed 's/;//')"
  result="$(./test "$test_file" "$expected_result")"
  if [ "$result" = "true" ]; then
    passed_tests=$(($passed_tests + 1))
  else
    echo "Test $test_file failed!"
    echo
  fi
done

if [ $passed_tests -eq $TESTS_NUMBER ]; then
  echo "$0: All tests passed!"
else
  echo "$0: Testing finished: $passed_tests out of $TESTS_NUMBER tests passed!"
fi
